language: python
python:
  - 3.6
node_js:
- '10'
branches:
  only:
  - master
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
- deps='pip numpy pandas scikit-learn coverage nose matplotlib'
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
- source activate test-environment
- conda install -c conda-forge jupyterlab=2.1.2
- python -m pip install -e .
- npm update
- jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
- jupyter labextension install ./js
- cd end_to_end_testing
install:
- npm install
script:
- npm test
#- npm run coveralls
