sudo: false
language: node_js
python:
- "3.6"
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get update
- sudo apt-get install python3
- python -m pip install jupyterlab
- python -m pip install -e .
- npm update
- jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
- jupyter labextension install ./js
- cd end_to_end_testing
install:
- npm install
script:
- npm test
#- npm run coveralls
