#!/bin/bash

# don't reinstall?
# pip install -e .

jupyter nbextension install --py --symlink --sys-prefix widget_cookie_cutter_test
jupyter nbextension enable --py --sys-prefix widget_cookie_cutter_test
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install ./js
