#!/bin/bash

# don't reinstall?
pip install -e .

# try upgrading jupyterlab
# conda install jupyterlab>=2.1.2

# jupyter nbextension install --py --symlink --sys-prefix widget_cookie_cutter_test
# jupyter nbextension enable --py --sys-prefix widget_cookie_cutter_test
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install ./js
